### ISSUE TITLE
Sync of a branch triggering build of branches

### ISSUE THREAD

**Issue by ch-acctg** [mjdetullio/multi-branch-project-plugin#104]
Hi, we are using 0.3 on 1.628 and I am unclear if the plugin is functioning as expect.  Right now we have sync set to * * * * * and new check ins to existing git branches are not building.  So is this expected behavior?  If so, how do we trigger builds on check in with this plugin.

Thanks!

**Comment by mjdetullio** [comment]
You need to set the Poll SCM trigger, not change the Sync Branches cron.  The former checks the branch for changes and the latter is the schedule that the list of branches gets updated.  You should never set your cron to ```* * * * *``` for any setting since at can put too much load on your SCM server or potentially overload Jenkins with polling threads.
