### ISSUE TITLE
How to call Multi Branch jobs  as a Downstream project 

### ISSUE THREAD

**Issue by narin-kura** [mjdetullio/multi-branch-project-plugin#114]
Here is the scenario . 
Currently we are creating branches through jenkins . 
once the new branch is created we are trying to call the Downstream projects using testapp/release/${releaseversio} where release version is the new branch created. 

Branch is created successfully and even the  Jenkins job has been created . but we are unable to call the job as downstream project

**Comment by narin-kura** [comment]
This is Regarding compatibility of 2 jenkins plugins  

trigger parameterized Build - used for configuring Upstream and Downstream and parallel Jenkins projects execution . 
Multi branch plugin - which will create a new job each and every job 

I Have a job A ( Normal job) Job B ( multi branch plugin ) creates sub projects based on branches. jobB/r1/0.2, jobB/r1/0.3 where r1/x.x is the branch name . 

Once I finish JOb A , based on few paramters and inputs in JOB A I need to call JOB B's subproject r1/0.2 or r1/0.3 

Problem is when i am trying to call jobB/r1/0.2 using Parametrized build plugin it fails throws an error showing 

Problems occurs: hudson.AbortException: Build aborted. Can't trigger undefined projects. 1 of the below project(s) can't be resolved:


Upon research i realised that "/" in job B's subproject name is creating issue . 

Can anyone provide a work around ?

**Comment by Xleek** [comment]
I have a quite similar issue where I have both A and B multi branch projects (both have the same branches name, ex: "a" and "b"), and I'd like to setup A/a to trigger the B/a project, (the idea is to get this for all branches, A/b -> B/b, A/c -> B/c etc...).

Ideally, it'd be really nice to be able to setup the same thing the other way (build a "B/a" project when upstream project "A/a" is done)

I don't really know if jenkins and the multibranch plugin allow this, but a solution could be to have a "reference project name" like "Project-branch" instead of "Project/branch" ?

**Comment by bmerry** [comment]
I need something similar to @Xleek. I won't have time to try this for a while, but I wonder if a workaround in the meantime is to set "Trigger builds remotely" on the downstream project, and then add a build step to the upstream project to poke the right URL?

**Comment by Thorndike** [comment]
I do need some kind of project linking like @Xleek described.

**Comment by jggc** [comment]
I'm having the exact same use case :
- Project A
    - Branch version/1
    - Branch version/2
- Project B
    - Branch version/1
    - Branch version/2

Project B depends on Project A.

So I want Project B version/1 to be built when Project A version/1 is built, and the same with version/2.

**I am willing to work on implementing this feature but I would need some pointers.** For now the way I think of implementing it is to add a "Build after multi branch project is built, matching branch names" in the build triggers section.

**Comment by mjdetullio** [comment]
Fixed in 0.4

**Comment by bmerry** [comment]
How does one trigger a downstream project with matching branch name? I didn't see anything new in the user interface for this in 0.4. Thanks.

**Comment by mjdetullio** [comment]
There is nothing new.  Existing Jenkins APIs should now work properly when trying to set downstream jobs that have slashes, since the slashes are now encoded.

There are no additional configuration options that cater specifically to the complex scenarios mentioned in previous comments.  This plugin isn't designed to manage workflows.
