### ISSUE TITLE
Support for webhooks?

### ISSUE THREAD

**Issue by mtscout6** [mjdetullio/multi-branch-project-plugin#12]
Ideally I'd like to avoid having Jenkins doing polling jobs, since this can cause a lot of overhead for the Jenkins server. With github at least there are options for webhooks to poke Jenkins. The events in Github's webhooks include: create, delete (branch add/removal), push (when commits are pushed). I think the webhooks with a longer polling interval would help alleviate the load on the jenkins server.

**Comment by skimmmer** [comment]
@mtscout6 I'm not sure if you got webhooks conencted, but at least in my attempts I get a 404 when I visit the URL specified.
If I check the "Trigger builds remotely (e.g., from scripts)" option, fill in a token, and then visit the "JENKINS_URL/job/JOB_NAME/branch/template/build?token=TOKEN_NAME" link, I get a 404. It also seems the path is different from the usual project path ("JENKINS_URL/job/JOB_NAME/build?token=TOKEN_NAME").
@mjdetullio Is this operational? If so, does it build all branches, or are there arguments?
Thanks!

**Comment by skimmmer** [comment]
Nevermind, using the Poll SCM method with no cron schedule and the "JENKINS/git/notifyCommit?url=GIT_URL" works fine.

**Comment by NicholasMerrill** [comment]
Instead of `JENKINS_URL/job/JOB_NAME/branch/template/build?token=TOKEN_NAME` it seems you must call `JENKINS_URL/job/JOB_NAME/branch/BRANCH_NAME/build?token=TOKEN_NAME`.

Notice the substitution of `BRANCH_NAME` for `template`.

**Comment by mtscout6** [comment]
I ended up getting pulled of the project I was working on and Jenkins is on hold for us until later this year. We are currently using TeamCity and plan to change to Jenkins, timing just hasn't been in our favor.

**Comment by nszceta** [comment]
This is a serious issue and I wasted many hours over the last few months because the URL hint for this plugin in Jenkins does does not work and it is grossly misleading.

**"template"** in:
`JENKINS_URL/job/JOB_NAME/branch/template/build?token=TOKEN_NAME`

should be replaced with **"BRANCH_NAME"**
`JENKINS_URL/job/JOB_NAME/branch/BRANCH_NAME/build?token=TOKEN_NAME`

However this solution is a non-starter because you have to enumerate each branch in your script. This is completely unacceptable.

The only "solution" that currently exists is what @skimmmer posted above:
[use] the Poll SCM method with no cron schedule and `JENKINS_URL/git/notifyCommit?url=GIT_URL`

**Comment by kibotu** [comment]
JENKINS_URL/job/JOB_NAME/branch/BRANCH_NAME/build works fine thanks :)

**Comment by mjdetullio** [comment]
```notifyCommit``` and ```build?token=``` are two different APIs that should be used for different purposes, with the latter being purely a build trigger for the specified branch project at the time of accessing the URL.  SCM related tasks should be handled by notifyCommit or other SCM mechanisms.

Closing this and opening a new issue #71
