### ISSUE TITLE
Why is 'Configure' offered at sub-project level?

### ISSUE THREAD

**Issue by DavidA2014** [mjdetullio/multi-branch-project-plugin#122]
Hi

This plugin is a great help for our situation, thank you for it.

I'm just a little confused about project configurations. The plugin's web page states:

' The project will use this SCM to automatically poll for a list of current branches and sync all the configuration to sub-projects.'

So I was expecting to only see 'Configure' offered for the top-level project, not for the sub-project of each branch. Then I found that I can set 'Check-out Strategy' in the sub-project configuration but not at the top-level. I would prefer to set that option once at the top-level.

Any thoughts?

Best regards

David

**Comment by mjdetullio** [comment]
Originally, configuring the sub-project level was not possible.  Since then, some restructuring in the way that the plugin works had to remove the restriction (in favor of improved functionality and features).  Since then it looks like https://github.com/jenkinsci/cloudbees-folder-plugin/blob/cloudbees-folder-5.1/src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java might be an API worth using to accomplish this.

**Comment by mjdetullio** [comment]
Apparently misunderstood the docs for ComputedFolder, appears not offering the configure option is a suggestion and not enforced by the folder.

Regardless, still going to introduce the API
