### ISSUE TITLE
Incorrect workspace path: forward slash incorrectly used on Windows slave

### ISSUE THREAD

**Issue by DavidA2014** [mjdetullio/multi-branch-project-plugin#132]
I have a multi-branch project that runs on a Windows slave.  Using version of 0.3 of the multi-branch-project-plugin, a certain branch resulted in this workspace path:

"C:\Jenkins\workspace\VS2010_all_branches_and_trunk\branches\TRY_TML_FD_17Sept2015"

Since upgrading to version 0.4.1, the path is now:

"C:\Jenkins\workspace\VS2010_all_branches_and_trunk\branches%2FTRY_TML_FD_17Sept2015"

This weirdly named path actually results in a broken build.  My compiler doesn't like it. 

It seems that the separator between 'branches' and the branch name is the ascii code for '/', when a '\' should be used on Windows.  Is this a bug?

I am running Jenkins 1.642.

**Comment by mjdetullio** [comment]
If "branches/" is part of your SCM's actual branch name, then this is intended.  Before 0.4.x all job names were only encoded for the configuration path on the master.  In 0.4.x the job names and paths are encoded, and the "real" names are set as the display name.  Since the job name is now encoded, the part of core Jenkins that is creating your workspace directory is using the encoded name for that directory.

**Comment by DavidA2014** [comment]
Hi Matthew, thanks for your reply. I'm afraid I don't really understand what you wrote, nor do I know how to fix my problem.  

I don't want a workspace directory that has an encoded forward slash, i.e. that looks like:

"C:\Jenkins\workspace\VS2010_all_branches_and_trunk\branches%2FTRY_TML_FD_17Sept2015"

To me, the layout with 0.3 was cleaner.

My Jenkins project name is:

VS2010_all_branches_and_trunk

In the configuration of this Jenkins project the Subversion 'Project Repository Base' is:

https://<ip addr>/subversion/myProj/

and 'Include branches' is set to:

trunk,branches/*

The actual repository path of the branch is:

https://<ip addr>/subversion/myProj/branches/TRY_TML_FD_17Sept2015

How could I change the Jenkins configuration to avoid the encoded forward slash '%2F' ?

Best regards
David

**Comment by mjdetullio** [comment]
It is not configurable and the change was required to fix numerous other
bugs

**Comment by DavidA2014** [comment]
My Linux gcc jobs work ok with this change, but our MSBuild jobs on Windows give errors. I don't know how I could escape the directory name to fix this.

May I make a suggestion?  Could you simply replace the '/' by '_' instead of encoding it with '%2F' ?

**Comment by wwasser** [comment]
Had the same Problem with usage of Multi-Branch Project. My branch names are following "http://nvie.com/posts/a-successful-git-branching-model/" so they are release/..., feature/..., ...
This works fine on project creation, but maven build fails due to this url encoded directoy names.

So maybe it's possible to provide user with at least project directory naming options:
* Convert to url encoded name
* Replace special characters with e.g. '_'
* Provide script to do custom naming

It's no problem to use real branch names in display name - main problem is the file system.

Maybe this would best fit all needs.

**Comment by DavidA2014** [comment]
I get an error when I inspect the console of a running multi-branch job:

    HTTP ERROR 404
    Problem accessing /jenkins/job/<job name>/branch/branches%252F<branch name>/15/. Reason:

    Not Found

I guess this is also due to the encoded '/'.
