### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by clehene** [mjdetullio/multi-branch-project-plugin#39]
It looks like there are many issues without a response. I tried it, it doesn't work, but I'm not sure it's worth debugging if issues don't get answered.

**Comment by mjdetullio** [comment]
Yes, sort of.  As you may have deduced, this is a personal project.  When it was published I had much, much more time to work on it.

I have some unreleased development but due to the nature of the plugin, the implementation, and Jenkins' API, it has been more difficult to work on than previously thought.

Actually I was about to release a big update last weekend but I encountered a huge showstopper during testing.  I had to take a slightly different approach with my implementation but there is no upgrade path.  The upgrade to 0.2 would break all jobs made with the current 0.1.x versions.  I still haven't found a good solution for upgrades.

If I can get a working upgrade solution then the 0.2 release should fix some things and add some more functionality.

**Comment by clehene** [comment]
@mjdetullio perhaps make the new version have a different name (e.g. 2) instead so it could be tested side-by-side.

That said, it may be interesting to explore trying to make the plugin not be a job, so that it could be inserted into existing jobs. I do realize that may be complicated or impossible, but it's worth thinking about it.

I'm not sure if there's an equivalent plugin, however reducing the number of jobs by not having to do one per branch is useful.

**Comment by mdaguete** [comment]
@mjdetullio why don't you release your code in a 'experimental' branch to allow us to test and give you feedback  and some help ?

**Comment by mjdetullio** [comment]
I have pushed it to the 'dev' branch a few times, though I plan on force pushing over it again soon.  Currently it's not in a functional state.  I worked a little bit on determining the migration path last night and laid out some pseudo-code.  I'll be working again on it tonight and perhaps have it finished.

If I can do all the upgrade testing and do some of the finishing touches then there will be a release.  If not then it will be sometime later this week or next week (won't have time this weekend).

If you want to play with the experimental code then wait for one more push.  You probably won't get anywhere with the current dev branch.

**Comment by mjdetullio** [comment]
Made a lot of headway but still need to do some more testing and tidy up.  The migration and the basic internals appear to work after a couple initial tests.  With the new structure the config page needs reworked now too, so my current progress still isn't exactly usable.

**Comment by clehene** [comment]
@mjdetullio sounds good, once you have something that can be tested, I'll try helping with that

**Comment by mjdetullio** [comment]
Released 0.2
