### ISSUE TITLE
How to create a multi-branch-project via REST API?

### ISSUE THREAD

**Issue by AGoliath** [mjdetullio/multi-branch-project-plugin#49]
Hi,
I was wondering if it is possible to create a new multi-branch-project via POSTing a config.xml to http://JENKINS_URL/createItem?name=newJobName 

I tried playing around a bit, and the closest I came up with was:
Merging the config.xmls from the parent job and the master branch job (e.g: the parent config.xml did not contain any build steps, but the master branch job did). 
This will create the new job, but will state "SCM not configured". If you then klick on Configure, all the Git infos are pre-polulated, a click on "save" without any changes then seems to set up the parent job correctly, but build and post-build steps are still missing.

**Comment by mjdetullio** [comment]
You'll have to make two requests.  One to post to the URL you mention.  Don't try to add extra stuff, just use an XML format from another multi-branch project as an example.  This is where you will configure the SCM.

Your second request will be a POST to ```${JENKINS_URL}/job/${JOB_NAME}/template/config.xml```.  This is where the build steps are configured.  Make sure you do not set the SCM here.  And keep it disabled.  If you add an SCM it will break the job altogether (I might've tried to add a safeguard for that but I don't remember -- if I did your SCM block will get overwritten anyway so don't bother).  Leave it as NullSCM.  Use another template's config.xml as an example since it is different from the main job and slightly different from the sub-projects.

**Comment by AGoliath** [comment]
i never marked this one as closed, sorry for that! Works like a charm, thanks for the great plugin!
