### ISSUE TITLE
Cannot configure the SCM repo browser in the main job definition

### ISSUE THREAD

**Issue by harniman** [mjdetullio/multi-branch-project-plugin#56]
It can be configured in the branch jobs but then gets overridden.

**Comment by mjdetullio** [comment]
SCM options on multi-branch project configuration page are implemented by the SCM plugins themselves.  So, the ability to set it in the main configuration is left to the SCM maintainers.

The branch projects aren't meant to be configured directly (originally in v0.1.x you couldn't) but this had to be exposed in order to integrate better with the standard project types.

The point of the plugin is to automatically sync the branch projects with the main configuration, so I won't add support for overrides.
