### ISSUE TITLE
Instructions for including/excluding branches

### ISSUE THREAD

**Issue by lwhiteley** [mjdetullio/multi-branch-project-plugin#6]
Not very sure how to use the exclude branches option or how to set patterns.

i put a specific branch `gh-pages` in the text field and the job was still created for that branch.

Would be nice to see examples beside these text fields just like the `Sync Branches Schedule` configuration

**Comment by moshezvi** [comment]
Jenkins 1.607, plugin version 0.2.2, using Git
====================================
The include/exclude works, but the syntax is different from the one in the regular Git Plugin.
For example, when selecting SCM > Git >Branches to build, the branch specifier accepts a regular expression (e.g. :.*origin/(master|testing|testing-.*)
![image](https://cloud.githubusercontent.com/assets/4245672/7631841/fa381ad2-fa4f-11e4-86a5-b8ecfa1ef650.png)

Seems like in this plugin, the include/exclude uses a variant of shell expansion, so the equivalent is:
master testing testing-*
![image](https://cloud.githubusercontent.com/assets/4245672/7631903/8e50f400-fa50-11e4-9786-3441d8085d8a.png)

I'm having a bit of a hard time refining the regex, so that it meets only the required branches. Any clarification would be much appreciated.

**Comment by mjdetullio** [comment]
SCM options, including those on the multi-branch project configuration page, are implemented by the SCM plugins themselves.

**Comment by povilasb** [comment]
As @mjdetullio said exclude functionality was added to Git `2.3-beta` plugin. Latest plugin version by this day is `2.4`. 
Exclude branches work with regular expression patters which are separated by white spaces:
`1.x v1-feature/* v1-*` etc.

So, I guess this issue might be closed.
